### ISSUE TITLE
Make Python code PEP-8 compliant

### ISSUE THREAD

**Issue by vasekch** [cinek810/snow-grafana-proxy#15]
I just forked repo to contribute and I my editor shouts at me in rainbow colors as code does not much follow PEP8 standard: https://www.python.org/dev/peps/pep-0008/

I don't want to be too pedantic, but at least change indentation from tabs to 4 spaces.

There is a tool to check the code https://pep8.readthedocs.io/en/release-1.7.x/intro.html
All popular editors have linting plugins - I use Atom, for example.

**Comment by cinek810** [comment]
Thanks for fixing that! Merged in #18.
