### ISSUE TITLE
Lambda Python version

### ISSUE THREAD

**Issue by jangaraj** [cinek810/snow-grafana-proxy#6]
Could you create AWS Lambda python version, please?

**Comment by cinek810** [comment]
You mean AWS Lambda deployment package? Shouldn't be an issue. I'll add it.

**Comment by jangaraj** [comment]
Not a package, just a function:
- no daemon mode
- log to stdout
- minimize external libraries
- (some) settings from env variables
....

**Comment by cinek810** [comment]
I don't know AWS Lambda very well, why .zip package with all features does't meet your requrirements? Requests, json and sys packages are a must. Specification of queriees in environment variables will be a mess. For something very specific you can hardcode it starting with the version from 1st commits..

**Comment by jangaraj** [comment]
Functions should be fast because you are paying for execution time. And execution (daemon in your case) + logging (logging library in your case) is handled by AWS infrastructure. Sure, you can use json, requests and sys, etc.. Just try to minimize them, because you will have to upload them if they are not available by default. For example, you don't need `calendar`, because you can use already imported `time`:
```
>>> int(time.mktime(time.gmtime()))
1532200528
>>> calendar.timegm(time.gmtime())
1532200528
```

Example lambda function:
```
import json
from botocore.vendored import requests

def lambda_handler(event, context):
    if os.environ['DEBUG'] == 'true':
        print 'DEBUG: Starting'
    r = requests.get(
         url = os.environ['SERVICENOW_URL'],
         auth = requests.auth.HTTPBasicAuth(os.environ['SERVICENOW_LOGIN'], os.environ['SERVICENOW_PASSWORD']))
    snowJson = json.loads(r.text)
    # transform serviceJson into grafanaSimpleJson
    if os.environ['DEBUG'] == 'true':
        print 'DEBUG: response ' + str(grafanaSimpleJson)
    return {'statusCode': 200, 'body': grafanaSimpleJson}
```

**Comment by cinek810** [comment]
Is the execution time measured by cputime or just walltime ? The whole concept is that grafana makes calls to snow-grafana-proxy when refresh happens, so it has to keep listening on requests from grafana. Is it possible to configure aws lambda to start execution on tcp/http request ? If yes is it allowed to keep memory allocated between executions?

**Comment by jangaraj** [comment]
Total executions time. Minimum billable time is 100ms. Lambda function doesn't need to listen. There is another AWS component which listens (API Gateway) and which forward request to lambda (event, context variables). The function must be stateless, so if you need state, then you have to save it (DB, global cache). If you are thinking about the cache, then again you don't need to implement it - it's one click setting in the API Gateway and response will be cached.

**Comment by cinek810** [comment]
Sounds cool. Are those components available as free tier if I need it for test/dev?

**Comment by jangaraj** [comment]
Yes:
- API GW: free 1M API calls
- Lambda: 1M free requests per month and 400,000 GB-seconds of compute time per month

**Comment by cinek810** [comment]
WIP. Pushed some initial attempt to lambda branch.

**Comment by cinek810** [comment]
@jangaraj Do you have time to give it a try? I think that current state of lambda branch is workable, however, the main issue may be slow reply from ServiceNow which may make this expensive ~20-30 s per call for my developer instance.

**Comment by jangaraj** [comment]
Thank you, my quick notes:
- pip install botocore  (locally and you can develop it also locally + you don't need to include any library in the deployement package):
```
from botocore.vendored import requests
import json, logging
```
- it's not clear how to enable debug mode and where are logs going - I don't see them in the stdout
- code duplication: you don't need to deploy lambda function 2x - just once and you find in the URL, which function has been called

**Comment by cinek810** [comment]
@jangaraj  Two mentioned issues addressed. Logs are visibile - at least when I use test button over webinterface. I'm not sure if with apigateway it's possible to get the query URL and select function in code - I tried to get context where I had a hope to find those details but it wasn't there.
