### ISSUE TITLE
Spacing between columns

### ISSUE THREAD

**Issue by baffonso** [cinek810/snow-grafana-proxy#7]
Hi,

I am not sure if this is a Grafana issue or a code issue but spacing between columns is not equal when displaying multiple tables.

![image](https://user-images.githubusercontent.com/13850300/43097844-5c6435ce-8e8b-11e8-9f07-6784b4688490.png)

**Comment by baffonso** [comment]
What I mean in above image is for example the 'Description field columns' do not line up.  The last table is the worst in that Ticket Number and Opened By are closer to each other compared to the top two tables.

**Comment by cinek810** [comment]
The way it's displayed is mostly defined by table grafana plugin. Snow-grafana-proxy is only a data source for grafana. If you can check if you see trailing white spaces in responses (it's printed in debug mode to log/console) I can think about removing it... but maybe it should just be as it is returned from snow.

**Comment by cinek810** [comment]
Closing because of no reply for submitter for very long time.
